### ISSUE TITLE
Failure to build using 2.0.0-dev.69.5

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/sample-pop_pop_win#60]
Here's some of the output:

```
webdev serve
Crash when formatting: [Encoding] Unable to decode bytes as UTF-8.
RangeError (index): Invalid value: Not in range 0..268900, inclusive: 269720
#0      _StringBase.[] (dart:core/runtime/libstring_patch.dart:233:55)
#1      Source.getTextLine (package:kernel/ast.dart:5805:42)
#2      getSourceLine (package:front_end/src/fasta/messages.dart:27:9)
#3      format (package:front_end/src/fasta/command_line_reporting.dart:80:27)
#4      ProcessedOptions.format (package:front_end/src/base/processed_options.dart:204:9)
#5      ProcessedOptions.report (package:front_end/src/base/processed_options.dart:218:22)
#6      CompilerContext.report (package:front_end/src/fasta/compiler_context.dart:67:13)
#7      Loader.addMessage (package:front_end/src/fasta/loader.dart:258:20)
#8      Loader.addCompileTimeError (package:front_end/src/fasta/loader.dart:207:5)
#9      LibraryBuilder.addCompileTimeError (package:front_end/src/fasta/builder/library_builder.dart:89:12)
#10     SourceLoader.tokenize (package:front_end/src/fasta/source/source_loader.dart:174:17)
<asynchronous suspension>
#11     SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:192:26)
<asynchronous suspension>
#12     Loader.buildOutlines (package:front_end/src/fasta/loader.dart:176:13)
<asynchronous suspension>
#13     KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:235:24)
<asynchronous suspension>
#14     withCrashReporting (package:front_end/src/fasta/deprecated_problems.dart:69:24)
<asynchronous suspension>
#15     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:232:12)
<asynchronous suspension>
#16     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:113:32)
<asynchronous suspension>
#17     withCrashReporting (package:front_end/src/fasta/deprecated_problems.dart:69:24)
<asynchronous suspension>
#18     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:59:10)
<asynchronous suspension>
#19     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:42:18)
<asynchronous suspension>
#20     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:120:46)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:120:19)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _runZoned (dart:async/zone.dart:1516:10)
#26     runZoned (dart:async/zone.dart:1463:12)
#27     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:119:12)
#28     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:128:41)
#29     generateKernel (package:front_end/src/kernel_generator_impl.dart:41:32)
<asynchronous suspension>
#30     kernelForComponent (package:front_end/src/api_prototype/kernel_generator.dart:83:17)
<asynchronous suspension>
#31     SingleShotCompilerWrapper.compileInternal (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/vm/bin/kernel_service.dart:186:11)
<asynchronous suspension>
#32     Compiler.compile.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/vm/bin/kernel_service.dart:134:39)
#33     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#34     _rootRun (dart:async/zone.dart:1120:38)
#35     _CustomZone.run (dart:async/zone.dart:1021:19)
#36     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#37     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#38     _rootRun (dart:async/zone.dart:1124:13)
#39     _CustomZone.run (dart:async/zone.dart:1021:19)
#40     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#41     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#42     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#43     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#44     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)

Crash when compiling file:///Users/john/.pub-cache/global_packages/webdev/bin/webdev.dart.snapshot,
at character offset 268392:
RangeError (index): Invalid value: Not in range 0..268900, inclusive: 269720
#0      _StringBase.[] (dart:core/runtime/libstring_patch.dart:233:55)
#1      Source.getTextLine (package:kernel/ast.dart:5805:42)
#2      getSourceLine (package:front_end/src/fasta/messages.dart:27:9)
#3      format (package:front_end/src/fasta/command_line_reporting.dart:80:27)
#4      ProcessedOptions.format (package:front_end/src/base/processed_options.dart:204:9)
#5      ProcessedOptions.report (package:front_end/src/base/processed_options.dart:218:22)
#6      CompilerContext.report (package:front_end/src/fasta/compiler_context.dart:67:13)
#7      Loader.addMessage (package:front_end/src/fasta/loader.dart:258:20)
#8      Loader.addCompileTimeError (package:front_end/src/fasta/loader.dart:207:5)
#9      LibraryBuilder.addCompileTimeError (package:front_end/src/fasta/builder/library_builder.dart:89:12)
#10     SourceLoader.tokenize (package:front_end/src/fasta/source/source_loader.dart:174:17)
<asynchronous suspension>
#11     SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:192:26)
<asynchronous suspension>
#12     Loader.buildOutlines (package:front_end/src/fasta/loader.dart:176:13)
<asynchronous suspension>
#13     KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:235:24)
<asynchronous suspension>
#14     withCrashReporting (package:front_end/src/fasta/deprecated_problems.dart:69:24)
<asynchronous suspension>
#15     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:232:12)
<asynchronous suspension>
#16     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:113:32)
<asynchronous suspension>
#17     withCrashReporting (package:front_end/src/fasta/deprecated_problems.dart:69:24)
<asynchronous suspension>
#18     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:59:10)
<asynchronous suspension>
#19     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:42:18)
<asynchronous suspension>
#20     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:120:46)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:120:19)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _runZoned (dart:async/zone.dart:1516:10)
#26     runZoned (dart:async/zone.dart:1463:12)
#27     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:119:12)
#28     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:128:41)
#29     generateKernel (package:front_end/src/kernel_generator_impl.dart:41:32)
<asynchronous suspension>
#30     kernelForComponent (package:front_end/src/api_prototype/kernel_generator.dart:83:17)
<asynchronous suspension>
#31     SingleShotCompilerWrapper.compileInternal (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/vm/bin/kernel_service.dart:186:11)
<asynchronous suspension>
#32     Compiler.compile.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/vm/bin/kernel_service.dart:134:39)
#33     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#34     _rootRun (dart:async/zone.dart:1120:38)
#35     _CustomZone.run (dart:async/zone.dart:1021:19)
#36     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#37     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#38     _rootRun (dart:async/zone.dart:1124:13)
#39     _CustomZone.run (dart:async/zone.dart:1021:19)
#40     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#41     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#42     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#43     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#44     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)


#0      format (package:front_end/src/fasta/command_line_reporting.dart:123:5)
#1      ProcessedOptions.format (package:front_end/src/base/processed_options.dart:204:9)
#2      ProcessedOptions.report (package:front_end/src/base/processed_options.dart:218:22)
#3      CompilerContext.report (package:front_end/src/fasta/compiler_context.dart:67:13)
#4      Loader.addMessage (package:front_end/src/fasta/loader.dart:258:20)
#5      Loader.addCompileTimeError (package:front_end/src/fasta/loader.dart:207:5)
#6      LibraryBuilder.addCompileTimeError (package:front_end/src/fasta/builder/library_builder.dart:89:12)
#7      SourceLoader.tokenize (package:front_end/src/fasta/source/source_loader.dart:174:17)
<asynchronous suspension>
#8      SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:192:26)
<asynchronous suspension>
#9      Loader.buildOutlines (package:front_end/src/fasta/loader.dart:176:13)
<asynchronous suspension>
#10     KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:235:24)
<asynchronous suspension>
#11     withCrashReporting (package:front_end/src/fasta/deprecated_problems.dart:69:24)
<asynchronous suspension>
#12     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:232:12)
<asynchronous suspension>
#13     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:113:32)
<asynchronous suspension>
#14     withCrashReporting (package:front_end/src/fasta/deprecated_problems.dart:69:24)
<asynchronous suspension>
#15     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:59:10)
<asynchronous suspension>
#16     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:42:18)
<asynchronous suspension>
#17     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:120:46)
#18     new Future.sync (dart:async/future.dart:224:31)
#19     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:120:19)
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _runZoned (dart:async/zone.dart:1516:10)
#23     runZoned (dart:async/zone.dart:1463:12)
#24     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:119:12)
#25     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:128:41)
#26     generateKernel (package:front_end/src/kernel_generator_impl.dart:41:32)
<asynchronous suspension>
#27     kernelForComponent (package:front_end/src/api_prototype/kernel_generator.dart:83:17)
<asynchronous suspension>
#28     SingleShotCompilerWrapper.compileInternal (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/vm/bin/kernel_service.dart:186:11)
<asynchronous suspension>
#29     Compiler.compile.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/vm/bin/kernel_service.dart:134:39)
#30     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#31     _rootRun (dart:async/zone.dart:1120:38)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#34     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#35     _rootRun (dart:async/zone.dart:1124:13)
#36     _CustomZone.run (dart:async/zone.dart:1021:19)
#37     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#38     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#39     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#40     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#41     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

Not sure if this is a Dart 2 or just an issue with this app.  Thanks!

**Comment by johnpryan** [comment]
upgrading to webdev 0.2.3+2 fixed the issue :)

**Comment by kevmoo** [comment]
Awesome! Just digging in here.
